<?php
/**
 * Created by PhpStorm.
 * User: MinhDuc
 * Date: 6/9/2020
 * Time: 2:34 PM
 */

namespace app\modules\gisposts\base;

use app\services\DebugService;
use app\services\UtilService;
use yii\filters\AccessControl;
use yii\web\Controller;
use Yii;

class AbstractController extends Controller
{

//    public function beforeAction($action)
//    {
//        $this->view->params['saphethan'] = UtilService::thongbaosaphethan();
//        return parent::beforeAction($action); // TODO: Change the autogenerated stub
//    }

    public function behaviors()
    {

        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => [
                            'index','create','update','view','delete','logout','getdata','update-test','browse'
                        ], // add all actions to take guest to login page
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
                'denyCallback' => function () {
                    return \Yii::$app->response->redirect(['cms/auth/login']);
                },
            ]
        ];
    }

    public function actions()
    {
        $this->layout = "@app/modules/gisposts/views/layouts/main";
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'view' => '@app/modules/gisposts/views/site/error',
                'layout' => "@app/modules/gisposts/views/layouts/main",
            ],
            // ...
        ];
    }

}