<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_chuyengia".
 *
 * @property integer $id_cg
 * @property integer $id_lvql
 * @property integer $id_dvct
 * @property integer $id_hh
 * @property integer $id_hv
 * @property string $chuyen_mon
 * @property string $ten_hh
 * @property string $ten_hv
 * @property string $ten_dvct
 * @property string $ten_lvql
 * @property string $ho_ten
 * @property integer $nam_sinh
 * @property integer $gioi_tinh
 * @property string $donvi_congtac
 * @property string $chuc_vu
 * @property string $dinh_huong
 * @property string $congtrinh_nghiencuu
 * @property string $dia_chi
 * @property string $dien_thoai
 * @property string $email
 * @property string $ghi_chu
 * @property string $geom
 * @property double $geo_x
 * @property double $geo_y
 */
class VChuyengia extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'v_chuyengia';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['id_cg', 'id_lvql', 'id_dvct', 'id_hh', 'id_hv', 'nam_sinh', 'gioi_tinh'], 'integer'],
            [['geom','dinh_huong','congtrinh_nghiencuu'], 'string'],
            [['geo_x', 'geo_y'], 'number'],
            [['chuyen_mon'], 'string', 'max' => 300],
            [['ten_hh', 'ten_hv', 'ten_dvct', 'ten_lvql', 'ho_ten', 'dien_thoai', 'email','chuc_vu'], 'string', 'max' => 100],
            [['donvi_congtac', 'dia_chi', 'ghi_chu'], 'string', 'max' => 500],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id_cg' => 'Id Cg',
            'id_lvql' => 'Id Lvql',
            'id_dvct' => 'Id Dvct',
            'id_hh' => 'Id Hh',
            'id_hv' => 'Id Hv',
            'chuyen_mon' => 'Chuyên ngành',
            'ten_hh' => 'Học hàm',
            'ten_hv' => 'Học vị',
            'ten_dvct' => 'Loại hình tổ chức',
            'ten_lvql' => 'Lĩnh vực quản lý',
            'ho_ten' => 'Họ tên',
            'nam_sinh' => 'Năm sinh',
            'gioi_tinh' => 'Giới tính',
            'donvi_congtac' => 'Đơn vị công tác',
            'dia_chi' => 'Địa chỉ',
            'dien_thoai' => 'Điện thoại',
            'email' => 'Email',
            'ghi_chu' => 'Ghi chú',
            'chuc_vu' => 'Chức vụ',
            'congtrinh_nghiencuu' => 'Công trình nghiên cứu',
            'dinh_huong' => 'Định hướng nghiên cứu',
            'geom' => 'Geom',
            'geo_x' => 'Kinh độ',
            'geo_y' => 'Vĩ độ',
        ];
    }

    public static function primaryKey() {
        return ['id_cg']; // TODO: Change the autogenerated stub
    }

}
