<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_vatlieusanpham".
 *
 * @property integer $id_pl
 * @property integer $id_cl
 * @property string $ten_pl
 * @property string $ten_cl
 */
class VVatlieusanpham extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_vatlieusanpham';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_pl', 'id_cl'], 'integer'],
            [['ten_pl', 'ten_cl'], 'string', 'max' => 300],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_pl' => 'Id Pl',
            'id_cl' => 'Id Cl',
            'ten_pl' => 'Tên phân loại',
            'ten_cl' => 'Tên chủng loại',
        ];
    }
     public static function primaryKey() {
        return ['id_pl']; // TODO: Change the autogenerated stub
    }
}
